/**
 * generated by Xtext
 */
package org.xtext.istic.soda.validation;

import org.xtext.istic.soda.validation.AbstractSoDaValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SoDaValidator extends AbstractSoDaValidator {
}
