/*
 * generated by Xtext
 */
package org.xtext.istic.soda.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SoDaUiModule extends org.xtext.istic.soda.ui.AbstractSoDaUiModule {
	public SoDaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
