/*
* generated by Xtext
*/
package org.xtext.istic.mapUI;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MapUIUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.istic.mapUI.ui.internal.MapUIActivator.getInstance().getInjector("org.xtext.istic.mapUI.MapUI");
	}
	
}
