/*
 * generated by Xtext
 */
package org.xtext.istic.soda.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.istic.soda.ui.internal.SoDaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SoDaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SoDaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SoDaActivator.getInstance().getInjector(SoDaActivator.ORG_XTEXT_ISTIC_SODA_SODA);
	}
	
}
