/*
 * generated by Xtext
 */
package org.xtext.istic.mapUI.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MapUIUiModule extends org.xtext.istic.mapUI.ui.AbstractMapUIUiModule {
	public MapUIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
