/*
* generated by Xtext
*/
package org.xtext.istic.mapUI.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MapUIAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/istic/mapUI/parser/antlr/internal/InternalMapUI.tokens");
	}
}
