/*
* generated by Xtext
*/
package org.xtext.istic.soda;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SoDaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.istic.soda.ui.internal.SoDaActivator.getInstance().getInjector("org.xtext.istic.soda.SoDa");
	}
	
}
