/**
 * generated by Xtext
 */
package org.xtext.istic.mapUI.validation;

import org.xtext.istic.mapUI.validation.AbstractMapUIValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MapUIValidator extends AbstractMapUIValidator {
}
