/**
 * generated by Xtext
 */
package org.xtext.istic.soda.ui.contentassist;

import org.xtext.istic.soda.ui.contentassist.AbstractSoDaProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SoDaProposalProvider extends AbstractSoDaProposalProvider {
}
