/**
 * generated by Xtext
 */
package org.xtext.istic.mapUI.ui.contentassist;

import org.xtext.istic.mapUI.ui.contentassist.AbstractMapUIProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MapUIProposalProvider extends AbstractMapUIProposalProvider {
}
