/*
 * generated by Xtext
 */
package org.xtext.istic.soda;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SoDaRuntimeModule extends org.xtext.istic.soda.AbstractSoDaRuntimeModule {

}
