/*
* generated by Xtext
*/
package org.xtext.istic.soda.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.istic.soda.services.SoDaGrammarAccess;

public class SoDaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SoDaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.istic.soda.parser.antlr.internal.InternalSoDaParser createParser(XtextTokenStream stream) {
		return new org.xtext.istic.soda.parser.antlr.internal.InternalSoDaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Soda";
	}
	
	public SoDaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SoDaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
