/*
 * generated by Xtext
 */
package org.xtext.istic.mapUI;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapUIRuntimeModule extends org.xtext.istic.mapUI.AbstractMapUIRuntimeModule {

}
