/*
 * generated by Xtext
 */
package org.xtext.istic.mapUI.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.istic.mapUI.ui.internal.MapUIActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MapUIExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MapUIActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MapUIActivator.getInstance().getInjector(MapUIActivator.ORG_XTEXT_ISTIC_MAPUI_MAPUI);
	}
	
}
